language: node_js
node_js:
  - "6.9.1"
install:
- pip install --user awscli
script:
- make build
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then make deploy; fi
branches:
  only:
  - master
env:
  global:
  - secure: uJEWhN92+7CH1S8JHOBMcXdG1eK+zTwD/swKLKLWWJFhdPYgokZqIKxHQFLgm+tuFO9U6rA32j6TtT97Ddk7P54uCNjeG66JZK3vObjRcJD2YNhxlvHq38gsm1aWfPez045nXjXIsSX04b1zgQPx+TYspv4Yl6jibmyJlc3rvJeSu06zFA2AFKq+eSMArXAYHJ4gfRAcnTKK9M9L58YUrPzMJJU4jldRD9Ik7FHyfnUVPHtyOewq/oJixRK1JQjNjpGOF9tYx39/6dAHfi8RbicrahpHJvGa3uR0AACXuLzjlARdlgqFNO1PTEcnIOptwTF8kCetlPZwImNBuGv1zrXHSUfePoXB0yNEpqQNSXfLZXPc9dlHVhNv/XHN7AHSO9qQ34+E2xuWUOPF6bJIPik51OsWfV5cHNp7XLX5PzgjYEypWNhrHtpKWRCgZ3MRJ+rrGz11YQ8LtcalFUlVpGNCgiMN6AYZGqZ5zEWOJrpymijdLy12/pnZLVw04F8U8ovCIOaebkQQpz5yfOvMlnR7jnpNE5Ye0cRpB9t9T2yfF6+VD2o1Tz0391uav5mvYCliYw4rVthOs99XtvgGyCtucuSvEoGCEYFynPzB0reW6NvdAsJ1UlKmKuv0zyVkI/qhuvO7LgdNKI/CqageYNEKE0vjOzFVY7U4mYMiHko=
  - secure: XpPCv4dRUXbHaKkkhD9s/NoS1DQfWt4zB1l/7ZkkZgzvBbyBU4qzZFZoE5qkS033kusLSHEiS3/HN2O47P0sRwedETOSd7N+RkadTG0Gl6PqHJEJCPqZV9x6+okay9zPLb0DpvdNYAgjs6HFtawJdr4w7LsXMmM7PV/3Nan8sZxKMusICSKmiFIFAp/FMPArQDsme9jBQ2awrj2dJn8j6FZfktoeJt/+jzvrmBNrkU2WfPy+OhX7hHdIMR29fJ9yEwmPMDmAX5k+aj/i9q+R7x0omYTNrk/GBNCHgExat33XFM7bH9B4+9kcuClZjmkur0/ynqSDT1VAfuLwXO/H5sG+OxeqRr1+SCQygw83mgI9gnvnvUOEFKFiIHVZ0P0sa1JvAotwzxgzB1a58u2tg/dK39dmu2UNZI8OCFOXls1xKmxuXzuju4bB8HIDYx8YV7PDZM2kkpK05NIirWODAeHiIZckQT9lr0LDa+CzBYKX41kiAZDHJ8RgEyrGoyxN+QoSRed/iJF6mpAZTS6uRq8w6FqYkejpsnGFLOqoldh1OqVof4i/ZGifaBq4UWgLCMD167sWQZg8ZZ2QqjTx/ninLhOtamulRz7K8iAlrlIZeheSVlTsuVyxjot4OQSEsid/aYTqgMGCFwBCLiu7bW7P1lwXEqwZy05/TuWNAyU=