baseURL = "https://www.threedevs.com/"
languageCode = "en-us"
title = "Three Devs"

copyright = "Copyright, Three Devs; all rights reserved."
canonifyurls = true
paginate = 3
theme = "hugo-bootstrap"

#disqusShortname = "xxxxxx"
googleAnalytics = "UA-128626176-1"

[manifest]
  name = "Three Devs"
  short_name = "Three-Devs"
  description = "Three developer friends."
  iconsSrc = ""
  theme_color = "#04e"
  background_color = "#eee"

[[menu.main]]
    name = "TAGS"
    pre = "<i class='fa fa-tags'></i>"
    weight = -110
    identifier = "tags"
    url = "/tags/"

[[menu.main]]
    name = "CATEGORIES"
    pre = "<i class='fa fa-folder-open'></i>"
    weight = -100
    identifier = "categories"
    url = "/categories/"

[[menu.main]]
    name = "ABOUT ME"
    pre = "<i class='fa fa-info-circle'></i>"
    weight = -90
    identifier = "about-me"
    url = "/page/about-me"

[[menu.footer]]
    name = "DISCLAIMER"
    weight = -110
    identifier = "disclaimer"
    url = "/page/disclaimer/"

[[menu.footer]]
    name = "LICENSE"
    weight = -120
    identifier = "license"
    url = "/page/license/"

[params.widgets]
  recent_articles = true
  categories = true
  tags = true
  tag_cloud = true
