# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Three Devs Theme"
license = "MIT"
licenselink = "https://github.com/Three-Devs/threedevs.com/blob/master/LICENSE"
description = ""
homepage = "http://threedevs.com/"
tags = []
features = []
min_version = "0.41"

[author]
  name = ""
  homepage = ""
